# Generated by Django 5.2.1 on 2025-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-due_date"]},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["-due_date"], name="tasks_task_due_dat_d9b31b_idx"
            ),
        ),
    ]
